version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - cd src/ts
      - npm install -g typescript
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - src/ts/package.json
    - src/ts/package-lock.json
    - 'src/tsbuild/**/*'
  discard-paths: yes