version: 0.2
runtime: python3
run:
  runtime-version: 3.12
  network: 
    port: 5000

phases:
  pre_build:
    commands:
      # Install AWS CLI for pushing the Docker image to ECR
      - yum install -y awscli
      
  build:
    commands:
      # Authenticate Docker to your ECR registry
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 253588643630.dkr.ecr.us-east-1.amazonaws.com
      
      - cd src/python

      # Build the Docker image
      - docker build --platform=linux/arm64 -t flaskapptest:latest .
      
      # Tag the Docker image with the ECR repository URI
      - docker tag flaskapptest:latest 253588643630.dkr.ecr.us-east-1.amazonaws.com/flaskapptest:tag

  post_build:
    commands:
      # Push the Docker image to ECR
      - docker push 253588643630.dkr.ecr.us-east-1.amazonaws.com/flaskapptest:tag