version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 253588643630.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker build -t flaskapp .

  post_build:
   commands:
      - echo Storing Docker image in S3...
      - docker save flaskapp:latest | gzip > docker_image.tar.gz
      - aws s3 cp docker_image.tar.gz s3://visited-flask-images/docker_image.tar.gz

artifacts:
  files:
    - docker_image.tar.gz