name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.AWS_ECR_REGION }}
          access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}

      - name: Build Docker image
        run: docker build -t flaskapp ./src/python

      - name: Tag Docker image
        run: docker tag flaskapp:latest ${{ secrets.AWS_ECR_REPO }}:app

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_ECR_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPO }}:app
