name: Backend Docker Build

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/frontend-ts

    steps:
      - uses: actions/checkout@v1

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and pull amplify
        run: |
          npm install -g @aws-amplify/cli
          amplify pull --appId d2rsi8yv6bvbyk --yes

      - name: install, build and test
        run: 
          npm install

      - name: configure amplify
        run: 
          amplify configure project

      - name: deploy
        run: 
          amplify publish --yes
