name: Backend Docker Build

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and pull amplify
        # uses: ambientlight/amplify-cli-action@0.3.0
        # with:
        #   amplify_command: configure
        #   amplify_env: prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          npm install -g @aws-amplify/cli
          amplify pull --appId d2rsi8yv6bvbyk --yes

      - name: install, build and test
        run: |
          cd src/frontend-ts
          npm install
          # build and test
          # npm run build
          # npm run test

      - name: configure amplify
        run: |
          cd src/frontend-ts
          amplify configure project

      - name: deploy
        # uses: ambientlight/amplify-cli-action@0.3.0
        # with:
        #   amplify_command: publish
        #   amplify_env: prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          cd src/frontend-ts
          amplify publish --yes
